MONGO_URI="ADD YOUR MONGO URI HERE"
MYSQL_CONFIG = {
    "ADD MYSQL CONFIG HERE"
}
JWT_SECRET_KEY = 'YOUR_JWT_SECRET_KEY'
TELEGRAM_BOT_TOKEN = 'your_telegram_bot_token'
TELEGRAM_CHAT_ID = 'your_chat_id'
